services:
  - type: web
    name: symfony-amj
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader && php bin/console cache:clear --env=prod && php bin/console cache:warmup --env=prod
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: amj-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: amj-db
    plan: free
    databaseName: amj_db
    user: amj_db_user

