services:
  - type: web
    name: symfony-amj
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: php -S 0.0.0.0:8000 -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: amj-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: amj-db
    plan: free
    databaseName: amj_db
    user: amj_db_user

